apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: kafka
    namespace: argocd
    labels:
        name: kafka
spec:
    project: default

    source:
        repoURL: https://github.com/GBrunelli/distributed-system
        targetRevision: HEAD
        path: ./infrastructure/modules/kafka

    destination:
        name: in-cluster
        namespace: kafka

    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
